# Generated by Django 4.1.3 on 2023-01-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='BannerCharacter',
        ),
    ]
