# Generated by Django 4.1.3 on 2023-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercharacter',
            name='banner',
            field=models.ManyToManyField(to='api.banner'),
        ),
    ]
