# Generated by Django 4.1.3 on 2023-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usercharacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCharacter',
        ),
    ]
