# Generated by Django 4.1.3 on 2023-01-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_usercharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('rarity', models.IntegerField(choices=[(1, 'UR'), (2, 'SSR'), (3, 'SR'), (4, 'R'), (5, 'N')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
