# Generated by Django 4.1.3 on 2023-01-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usercharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
